--EXCERCIE EXERCISE STORE PROCEDURE

--CÂU 1: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ TUỔI, GIỚI TÍNH. LẤY RA THÔNG TIN
--NHỮNG NHÂN VIÊN TƯƠNG ỨNG
	CREATE PROCEDURE VD01 (@TUOI INT,@GIOITINH CHAR(5),@THONGTINNV INT OUTPUT)
AS 
	BEGIN
		SET @THONGTINNV=(
					SELECT NV.* 
					FROM NHANVIEN NV
					WHERE (YEAR(GETDATE())-YEAR(NGAYSINH)) = @TUOI AND NV.GIOITINH=@GIOITINH
		) 
	END 
GO
	DECLARE @T  --KHAI BÁO 1 VIẾN TRUNG GIAN 
	EXECUTE VD01 @TUOI=50,@GIOITINH='F',@THONGTINNV =@T OUTPUT 
	PRINT N'THÔNG TIN NHỮNG NHÂN VIÊN LÀ'+CONVERT(CHAR(5),@T) 
GO
--CÂU 2: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ MADD, MAPHG LẤY RA THÔNG TIN NHỮNG
--DỰ ÁN TƯƠNG ỨNG

--CÂU 3: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ ĐỊA CHỈ, THAM SỐ RA LÀ TỔNG SỐ
--LƯƠNG NHÂN VIÊN ĐANG SỐNG TẠI ĐỊA CHỈ ĐÓ

--CÂU 4: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ MANV, THAM SỐ RA LÀ TỔNG SỐ GIỜ MÀ
--NHÂN VIÊN ĐÓ ĐÃ THAM GIA TẤT CẢ DỰ ÁN

--CÂU 5: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ TÊN NV, TÍNH TỔNG SỐ LƯỢNG DỰ ÁN
--MÀ NHÂN VIÊN ĐÓ ĐÃ THAM GIA

--CÂU 6: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ TENDD, TÍNH TỔNG SỐ LƯỢNG DỰ ÁN
--TRIỂN KHAI TẠI ĐỊA ĐIỂM ĐÓ

--CÂU 7: VIẾT STORE PROCE VỚI THAM SỐ VÀO LÀ TÊN NGƯỜI GIÁM SÁT, TÍNH TỔNG SỐ LƯỢNG
--NHÂN VIÊN CHỊU SỰ GIÁM SÁT CỦA TÊN NGƯỜI GIÁM SÁT ĐÓ

--CÂU 8: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ TÊN NGƯỜI GIÁM SÁT, LẤY RA THÔNG
--TIN NHỮNG NHÂN VIÊN CHỊU SỰ GIÁM SÁT CỦA TÊN NGƯỜI GIÁM SÁT ĐÓ

--CÂU 9: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ MANV, TENNV, LẤY RA THÔNG TIN
--NGƯỜI GIÁM SÁT CỦA NHÂN VIÊN ĐÓ

--CÂU 10: VIẾT STORE PROCEDURE VỚI THAM SỐ VÀO LÀ TUỔI, THAM SỐ RA LÀ TỔNG SỐ
--LƯỢNG NGƯỜI GIÁM SÁT >= TUỔI
